# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
