# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-26 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('kakao_id', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=30)),
                ('real_name', models.CharField(max_length=10)),
                ('agree_1', models.CharField(choices=[('Y', '예'), ('N', '아니오')], max_length=5)),
                ('agree_2', models.CharField(choices=[('Y', '예'), ('N', '아니오')], max_length=5)),
                ('agree_3', models.CharField(choices=[('Y', '예'), ('N', '아니오')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
