# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-28 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='agree_1',
            new_name='agree',
        ),
        migrations.RemoveField(
            model_name='register',
            name='agree_2',
        ),
        migrations.RemoveField(
            model_name='register',
            name='agree_3',
        ),
    ]
