# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-20 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', '자기소개서'), ('2', '합격수기'), ('3', '대학생활'), ('4', '영어'), ('5', '돈 버는 방법'), ('6', '마케팅'), ('7', '독후감'), ('8', '성공 이야기'), ('9', '심리 상담')], max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('score', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
