# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-28 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180521_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='admin/%Y/%m/%d'),
        ),
    ]
