# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-28 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180528_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='user',
            new_name='user_set',
        ),
    ]
